apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-exemple-platform-obs 
spec:
  selector:
    matchLabels:
      app: app-exemple-platform-obs
  template:
    metadata:
      labels:
        app: app-exemple-platform-obs
    spec:
      containers:
        - image: okteto.dev/java-gradle-app-exemple-platform-obs:1.0.0
          name: app-exemple-platform-obs

---

apiVersion: v1
kind: Service
metadata:
  name: app-exemple-platform-obs
spec:
  type: ClusterIP
  ports:
    - name: "app-exemple-platform-obs"
      port: 8080
  selector:
    app: app-exemple-platform-obs

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-exemple-platform-obs
  annotations:
    dev.okteto.com/generate-host: app-exemple-platform-obs
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: app-exemple-platform-obs
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific